// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all procedure arg schemas
import * as AskScrapsProcedure from "../ask_scraps_procedure";

export type AskScrapsArgs = __Infer<typeof AskScrapsProcedure.params>;
export type AskScrapsResult = __Infer<typeof AskScrapsProcedure.returnType>;

