// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import ClaimListingReducer from "../claim_listing_reducer";
import CompleteListingReducer from "../complete_listing_reducer";
import PostListingReducer from "../post_listing_reducer";
import SetNameReducer from "../set_name_reducer";
import UnclaimListingReducer from "../unclaim_listing_reducer";

export type ClaimListingParams = __Infer<typeof ClaimListingReducer>;
export type CompleteListingParams = __Infer<typeof CompleteListingReducer>;
export type PostListingParams = __Infer<typeof PostListingReducer>;
export type SetNameParams = __Infer<typeof SetNameReducer>;
export type UnclaimListingParams = __Infer<typeof UnclaimListingReducer>;

