// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  donor: __t.string(),
  description: __t.string(),
  pickupBy: __t.timestamp().name("pickup_by"),
  lat: __t.f64(),
  lng: __t.f64(),
  postedBy: __t.identity().name("posted_by"),
  claimedBy: __t.option(__t.identity()).name("claimed_by"),
  completed: __t.bool(),
});
