// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const ClaimAttempt = __t.object("ClaimAttempt", {
  listingId: __t.u64(),
  who: __t.identity(),
  won: __t.bool(),
  at: __t.timestamp(),
});
export type ClaimAttempt = __Infer<typeof ClaimAttempt>;

export const ExpiryTick = __t.object("ExpiryTick", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type ExpiryTick = __Infer<typeof ExpiryTick>;

export const Listing = __t.object("Listing", {
  id: __t.u64(),
  donor: __t.string(),
  description: __t.string(),
  pickupBy: __t.timestamp(),
  lat: __t.f64(),
  lng: __t.f64(),
  postedBy: __t.identity(),
  claimedBy: __t.option(__t.identity()),
  completed: __t.bool(),
});
export type Listing = __Infer<typeof Listing>;

export const Secret = __t.object("Secret", {
  name: __t.string(),
  value: __t.string(),
});
export type Secret = __Infer<typeof Secret>;

export const Suggestion = __t.object("Suggestion", {
  answer: __t.string(),
  listingId: __t.option(__t.u64()),
  failed: __t.bool(),
});
export type Suggestion = __Infer<typeof Suggestion>;

export const User = __t.object("User", {
  identity: __t.identity(),
  name: __t.string(),
});
export type User = __Infer<typeof User>;

