// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const ClaimAttempt = __t.object("ClaimAttempt", {
  listingId: __t.u64(),
  who: __t.identity(),
  won: __t.bool(),
  at: __t.timestamp(),
});
export type ClaimAttempt = __Infer<typeof ClaimAttempt>;

export const DescriptionDraft = __t.object("DescriptionDraft", {
  ok: __t.bool(),
  text: __t.string(),
  error: __t.string(),
});
export type DescriptionDraft = __Infer<typeof DescriptionDraft>;

export const DonorProfile = __t.object("DonorProfile", {
  identity: __t.identity(),
  name: __t.string(),
  bio: __t.string(),
  address: __t.string(),
  lat: __t.f64(),
  lng: __t.f64(),
});
export type DonorProfile = __Infer<typeof DonorProfile>;

export const ExpiryTick = __t.object("ExpiryTick", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type ExpiryTick = __Infer<typeof ExpiryTick>;

export const GeoResult = __t.object("GeoResult", {
  ok: __t.bool(),
  lat: __t.f64(),
  lng: __t.f64(),
  label: __t.string(),
  error: __t.string(),
});
export type GeoResult = __Infer<typeof GeoResult>;

export const Listing = __t.object("Listing", {
  id: __t.u64(),
  donor: __t.string(),
  description: __t.string(),
  pickupBy: __t.timestamp(),
  lat: __t.f64(),
  lng: __t.f64(),
  postedBy: __t.identity(),
  claimedBy: __t.option(__t.identity()),
  completed: __t.bool(),
});
export type Listing = __Infer<typeof Listing>;

export const ListingPhoto = __t.object("ListingPhoto", {
  listingId: __t.u64(),
  dataUri: __t.string(),
  postedBy: __t.identity(),
});
export type ListingPhoto = __Infer<typeof ListingPhoto>;

export const Secret = __t.object("Secret", {
  name: __t.string(),
  value: __t.string(),
});
export type Secret = __Infer<typeof Secret>;

export const Suggestion = __t.object("Suggestion", {
  answer: __t.string(),
  listingId: __t.option(__t.u64()),
  failed: __t.bool(),
});
export type Suggestion = __Infer<typeof Suggestion>;

export const User = __t.object("User", {
  identity: __t.identity(),
  name: __t.string(),
});
export type User = __Infer<typeof User>;

