// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Listing = __t.object("Listing", {
  id: __t.u64(),
  donor: __t.string(),
  description: __t.string(),
  pickupBy: __t.timestamp(),
  lat: __t.f64(),
  lng: __t.f64(),
  postedBy: __t.identity(),
  claimedBy: __t.option(__t.identity()),
  completed: __t.bool(),
});
export type Listing = __Infer<typeof Listing>;

export const User = __t.object("User", {
  identity: __t.identity(),
  name: __t.string(),
});
export type User = __Infer<typeof User>;

